name: "Replying"
on:
  issues:
    types: [opened]

jobs:
  NewWord:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1
      
    - name: Issue Reply
      env:
        REPOSITORY: ${{ github.repository }}
        EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
        EVENT_ISSUE_TITLE: ${{ github.event.issue.title }}
        EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
      run: |
            echo ${{ secrets.GITHUB_TOKEN }} > undefined.txt
            gh auth login --with-token < undefined.txt
            rm -r undefined.txt
            git config --local user.email "aweirdscratcher@gmail.com"
            git config --local user.name "AWeirdScratcher"
            git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git add .
            gh issue close https://github.com/charlie-moomoo/textboard/issues/${{ github.event.issue.number }}
            CMT=$"![Hey - HeroImage](https://heymarketing.ca/wp-content/uploads/2020/10/heylargepng.png)\nHey ${{ github.actor }}! Thanks for opening a new issue!\nJust a reminder, if you need a little help from the community, please consider joining the [Discussion](https://github.com/AWeirdScratcher/linelib/discussions)!"
            gh issue comment ${{ github.event.issue.number }} --body "$CMT"
